[package]
name = "rust_server"
version = "0.1.0"
authors = ["lyy128328 <jackliao831008@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
websocket = "0.20.2"
rust-crypto = "^0.2"
libsecp256k1 = "0.2.1"
hex = "0.3.2"